### ISSUE TITLE
Upload to AWS

### ISSUE THREAD

**Issue by cameronroe** [pjeby/gulpsmith#15]
You mention the use case for "Want to upload your Metalsmith build to Amazon S3 or send it someplace via SFTP without first generating files locally and then running a separate uploading process". 

How would one go about doing that? Do you have a simple example showcasing what you mean?

Thanks!

**Comment by pjeby** [comment]
Simply `.pipe()` your Metalsmith build results into an appropriately configured Gulp plugin. Googling "gulp s3" shows that there seem to be at least 4 modules which provide the ability to upload files to S3.  I have not used any of them, so you'll need to check their documentation and choose one that best suits your needs.

To integrate with Metalsmith, simply replace the `gulp.src().pipe(XXX)` in their examples with a call to `.use(gulpsmith.pipe(XXX))` in your Metalsmith build pipeline.  (I assume you're using Metalsmith as your primary build process, or else you'd have just looked for Gulp s3 modules in the first place.)

**Comment by cameronroe** [comment]
I know about gulp-s3, but I'm just wondering how it's used in the pipeline. There seems to be two ways to use gulpsmith either in a gulp pipeline or in a Metalsmith pipeline. Which would be the way where I can avoid writing to disk? Ideally I want to run this on a server and just run a gulp build to push to S3. Would this be possible with gulpsmith?

**Comment by pjeby** [comment]
Gulpsmith is a wrapper to convert plugins between systems, so you can either use a gulp plugin with metalsmith, or a metalsmith plugin with gulp.  Which way you prefer to do it is up to you, and whether it will work for you is dependent on your requirements and the tools.  I do not know whether you can have Metalsmith avoid writing files or not, but I do know that gulp *can* avoid that (because it doesn't write anything unless you tell it to).

So, if I were in your position I would probably just create a gulp pipeline and add metalsmith plugins in the middle.
